#!/usr/bin/env python3

import subprocess
import time

from typing import Generator


def main():
    stdout = get_music_status()
    previous_len = len(stdout)
    next_point = get_point(previous_len)
    while True:
        stdout = get_music_status()

        if len(stdout) != previous_len:
            previous_len = len(stdout)
            next_point = get_point(previous_len)

        point = next(next_point)

        if stdout == "No players found":
            print_music("No music")
            time.sleep(30)
            continue

        print_music(f"{stdout[point:]}    {stdout[:point]}"[:20])
        time.sleep(1)


def get_music_status():
    return subprocess.run(
        [
            "playerctl",
            "metadata",
            "--format",
            "{{ artist }} - {{ title }} ({{ duration(position) }}/{{ duration(mpris:length) }})",
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        universal_newlines=True,
    ).stdout.strip()


def get_point(max_len: int) -> Generator:
    while True:
        for i in range(max_len):
            yield i


def print_music(text: str) -> None:
    print(f"M{text}", flush=True)


if __name__ == "__main__":
    main()
