# ---------------------------------------------------------------------------
# Purpose: Per-application rules and workspace assignments. Use `assign` and
#          `for_window` blocks to control placement and floating behavior for
#          specific applications.
# ---------------------------------------------------------------------------

assign [app_id="librewolf"] "11:🌐:1"
assign [app_id="brave-browser"] "12:🌐:2"
assign [app_id="slack"] "31:💬:1"
assign [app_id="google-chrome"] "41:🍞:1"

for_window [window_role="pop-up"] floating enable
for_window [window_role="floating_con"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="dialog"] floating enable
for_window [window_type="dialog"] floating enable
for_window [title="discord.com/popout"] floating enable, border pixel 2
for_window [title="Huddle"] floating enable, border pixel 2
