# -------------------------------------------------------------------------
# Purpose: Theme and client appearance settings. Includes the color scheme
#          and defines wallpaper, client color rules and other visual
#          styling used by Sway.
# -------------------------------------------------------------------------

include colorscheme.conf

#                       Border  BG      Text    Ind     Child Border
client.focused          $base05 $base0D $base00 $base0D $base0D
client.focused_inactive $base01 $base01 $base05 $base03 $base01
client.unfocused        $base01 $base00 $base05 $base01 $base01
client.urgent           $base08 $base08 $base00 $base08 $base08

smart_borders on
gaps inner 10
gaps outer 5
