# ---------------------------------------------------------------------------
# Purpose: Define reusable variables (mod key, direction keys, terminal, etc.)
# ---------------------------------------------------------------------------

# Variables
set {
    # Logo key. Use Mod1 for Alt.
    $mod Mod4
    # Home row direction keys, like vim
    $left h
    $down j
    $up k
    $right l
    # Your preferred terminal emulator
    $term foot
}

# Workspaces start
set $ws11 "11: 🍞"
set $ws21 "21: 🌐"
set $ws31 "31: 💻"
set $ws41 "41: 💬"
# Workspaces end