# ---------------------------------------------------------------------------
# Purpose: Define reusable variables (mod key, direction keys, terminal, etc.)
# ---------------------------------------------------------------------------

# Variables
set {
    # Logo key. Use Mod1 for Alt.
    $mod Mod4
    # Home row direction keys, like vim
    $left h
    $down j
    $up k
    $right l
    # Your preferred terminal emulator
    $term foot
}

# Workspaces start
set $ws1 "11:🌐:1"
set $ws2 "21:💻:1"
set $ws3 "31:💬:1"
set $ws4 "41:🍞:1"
# Workspaces end
