#!/usr/bin/env sh
# extract - archive extractor
# usage: extract <file>

[ -f $1 ] || {
    printf '"%s" is not a valid file\n' "$1"
    exit 1
}

case "$1" in
    *.tar) tar xf $1 ;;
    *.tar.bz2|*.tbz2) tar xjf $1 ;;
    *.tar.gz|*.tgz) tar xzf $1 ;;
    *.bz2) bunzip2 $1 ;;
    *.rar) unrar x $1 ;;
    *.gz) gunzip $1 ;;
    *.zip) unzip $1 ;;
    *.Z) uncompress $1 ;;
    *.7z) 7z x $1 ;;
    *) printf '"%s" cannot be extracted via extract\n' "$1" ;;
esac
