#!/usr/bin/env sh
# telpipe - send notification with previous command output
# usage: <comand> | telpipe

[ "$(command -v send_telegram_message)" ] || {
    printf 'Could not find "send_telegram_message" required for this script. Exiting.\n' 
    exit 1
}

[ -t 0 ] && {
    printf 'Please, use this script piping something to it.\n'
    exit 1
}

read content
header='--------------------- Output ---------------------'
previous_output="$(printf '```\n%b\n%s\n```' "$header" "$content")"
send_telegram_message "$previous_output"
