;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-line
        drag-stuff-down
        drag-stuff-right
        drag-stuff-up
        end-of-visual-line
        indent-for-tab-command
        kill-region
        markdown-backward-paragraph
        markdown-forward-paragraph
        markdown-outdent-or-delete
        mouse-set-region
        org-cycle
        org-self-insert-command
        overwrite-mode
        py-electric-colon
        py-electric-delete
        py-indent-or-complete
        sh-assignment
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        end-of-buffer-other-window
        executable-interpret
        find-file
        ignore
        mouse-appearance-menu
        save-buffers-kill-terminal
        toggle-frame-fullscreen
        ))
