# Some useful scripts
[scripts-add_log_entry]
relpath = "scripts/add_log_entry"
description = "Append a new entry in GNU changelog style."
[scripts-colortrans]
relpath = "scripts/colortrans.py"
description = "Convert values between RGB hex codes and xterm-256 color codes."
[scripts-hex_dec_color]
relpath = "scripts/hex_dec_color.sh"
description = "Convert between decimal and hexadecimal"
[scripts-kb_light]
relpath = "scripts/kb_light.py"
description = "Modify keyboard backlight."
packages = ["python-dbus"]
[scripts-lock]
relpath = "scripts/lock.sh"
description = "Lock screen with a pixelated screenshot of your desktop."
packages = ["xorg-xdpyinfo", "maim", "imagemagick", "i3lock"]
[scripts-screenshot]
relpath = "scripts/screenshot"
description = "Select a square in your screen and save the capture in your clipboard."
packages = ["maim", "xclip"]
[scripts-screenshot-desktop]
relpath = ".local/share/applications/screenshot.desktop"
description = "Desktop entry for screenshot script."
[scripts-pomodoro]
relpath = "scripts/pomodoro.py"
description = "Run the Pomodoro technique and send notifications to Telegram."
[scripts-session]
relpath = "scripts/session.sh"
description = "Simple terminal GUI to suspend, restart or poweroff the system."
[scripts-show_keypress]
relpath = "scripts/show_keypress.sh"
description = "Show key press."
packages = ["xorg-xev"]
[scripts-show_sxhkd_keybindings]
relpath = "scripts/show_sxhkd_keybindings.sh"
description = "Capture and show sxhkd keybindings."
[scripts-status]
relpath = "scripts/status.sh"
description = "Check status of each git directory located in the current path."
packages = ["git"]
[scripts-tput_clock]
relpath = "scripts/tput_clock.sh"
description = "Show clock in an ascii banner."
packages = ["banner"]
[scripts-tput_color_base16]
relpath = "scripts/tput_color_base16.sh"
description = "Show base16 fg/bg color combinations."
[scripts-tput_color_table]
relpath = "scripts/tput_color_table.sh"
description = "Show all ANSI colors with their correspondent index."
[scripts-vm]
relpath = "scripts/vm"
description = "Manage VirtualBox VM running without GUI."
packages = ["virtualbox"]
[scripts-wm_selector]
relpath = "scripts/wm_selector.sh"
description = "Select window manager from tty"
packages = ["dialog"]
[scripts-xr_color_scheme]
relpath = "scripts/xr_color_scheme.sh"
description = "Show first 21 colors from Xresources."
[scripts-xr_wrapper_reloader]
relpath = "scripts/xr_wrapper_reloader.sh"
description = "Reload xrdb with custom script."
[scripts-bookmarks]
relpath = "scripts/bookmarks"
description = "Open bookmarks with the default web browser."
packages = ["yq"]

# Emacs configuration
[emacs-config]
relpath = ".emacs.d/config.org"
description = "Emacs editor main configuration file."
[emacs-init]
relpath = ".emacs.d/init.el"
description = "Emacs editor config.org loader."
[emacs-mc-lists]
relpath = ".emacs.d/.mc-lists.el"
description = "Emacs editor mc-lists plugging configuration."

# Editors
[nvim-init]
relpath = ".config/nvim/init.vim"
description = "Nvim configuration file."
packages = ["neovim"]
[vim-vimrc]
relpath = ".vimrc"
description = "Vim configuration file."
packages = ["vim"]

# File managers
[pcmanfm]
relpath = ".config/pcmanfm/default/pcmanfm.conf"
description = "LXDE file manager."
packages = ["pcmanfm"]

[ranger-commands]
relpath = ".config/ranger/commands.py"
[ranger-rc]
relpath = ".config/ranger/rc.conf"
[ranger-rifle]
relpath = ".config/ranger/rifle.conf"
[ranger-scope]
relpath = ".config/ranger/scope.sh"

# Git
[gitconfig]
relpath = ".gitconfig"
description = "Git global configuration."
packages = ["git", "dandavison/delta"]

[gitcommit]
relpath = ".gitcommit"
description = "Git commit message template."
packages = ["git"]

# Shell
[bash-bashrc]
relpath = ".bashrc"
description = "Main bash user configuration file."
[bash-profile]
relpath = ".bash_profile"
description = "Entrypoint for .bashrc file."

[shell-aliases]
relpath = ".shell_utilities/aliases.sh"
description = "Utils file where the alias are defined."
[shell-functions]
relpath = ".shell_utilities/functions.sh"
description = "Utils file where the functions are defined."
[shell-variables]
relpath = ".shell_utilities/variables.sh"
description = "Utils file where the variables are defined."
[shell-prompt]
relpath = ".shell_utilities/prompt.sh"
description = "Custom shell prompt."

[fish-config]
relpath = ".config/fish/config.fish"
description = "Fish shell main configuration file."
[fish-fishfile]
relpath = ".config/fish/fishfile"
description = "Fish shell file where the pluggins are defined."
packages = ["Fisher"]

# Terminals
[terminator-config]
relpath = ".config/terminator/config"
description = "Terminator configuration file."
packages = ["terminator"]

# Utils
[top-toprc]
relpath = ".config/procps/toprc"
description = "Top configuration file."

# Window managers config files

## Bspwm
[bspwm-autostart]
relpath = ".config/bspwm/autostart.sh"
description = "bspwm app-autostart script."
[bspwm-bspwmrc]
relpath = ".config/bspwm/bspwmrc"
description = "bspwm configuration file."
packages = ["bspwm"]

## Sxhkd
[sxhkd-sxhkdrc]
relpath = ".config/sxhkd/sxhkdrc"
description = "sxhkd configuration file."
packages = ["sxhkd"]

## Wal (pywal)
[wal-reload-services]
relpath = ".config/wal/reload_services.sh"
description = "Script to run after wal theme selection."
packages = ["python-pywal"]

## Rofi
[rofi-config]
relpath = ".config/rofi/config"
description = "Rofi configuration file."
packages = ["rofi"]
[rofi-config-wal-template]
relpath = ".config/wal/templates/colors-rofi-dark.rasi"
description = "Wal template for Rofi."
packages = ["python-pywal"]

## Dunst
[dunst-dunstrc]
relpath = ".config/dunst/dunstrc"
description = "Dunst notification daemon main configuration file."
packages = ["dunst"]
[dunst-dunstrc-wal-template]
relpath = ".config/wal/templates/colors-dunstrc"
description = "Dunst configuration template to use wal coloring. Don't use this one along with dunstrc file."
packages = ["python-pywall"]

## Polybar
[polybar-config]
relpath = ".config/polybar/config"
description = "Polybar main configuration file."
packages = ["aur/polybar"]

## Xresources
[xresources-edit]
relpath = ".Xresources.edit"
description = "Xresources script to safely edit .Xresources through .Xresources.src."
[xresources-src]
relpath = ".Xresources.src"
description = "Xresources brother."

# Tmux
[tmux-conf-local]
relpath = ".tmux.conf.local"
description = "Tmux personalization using oh my tmux config."
packages = ["tmux"]

[ncspot-config]
relpath = ".config/ncspot/config.toml"
description = "NCurses Spotify client."
packages = "ncspot"

