# Scripts
[bin-add_log_entry]
relpath = ".bin/add_log_entry"
description = "Append a new entry in GNU changelog style."
[bin-bookmarks]
relpath = ".bin/bookmarks"
description = "Open bookmarks with the default web browser."
packages = ["yq"]
[bin-kb_light]
relpath = ".bin/kb_light.py"
description = "Modify keyboard backlight."
packages = ["python-dbus"]
[bin-lock]
relpath = ".bin/lock.sh"
description = "Lock screen with a pixelated screenshot of your desktop."
packages = ["xorg-xdpyinfo", "maim", "imagemagick", "i3lock"]
[bin-pomodoro]
relpath = ".bin/pomodoro.py"
description = "Run the Pomodoro technique and send notifications to Telegram."
[bin-screenshot]
relpath = ".bin/screenshot"
description = "Select a square in your screen and save the capture in your clipboard."
packages = ["maim", "xclip"] 
[bin-send_telegram_document]
relpath = ".bin/send_telegram_document"
description = "Send a document to the telegram bot setted up."
packages = ["jq", "curl"]
[bin-send_telegram_message]
relpath = ".bin/send_telegram_message"
description = "Send a message to the telegram bot setted up."
packages = ["jq", "curl"]
[bin-screenshot-desktop]
relpath = ".local/share/applications/screenshot.desktop"
description = "Desktop entry for screenshot script."
[bin-session]
relpath = ".bin/session.sh"
description = "Simple terminal GUI to suspend, restart or poweroff the system."
[bin-show_keypress]
relpath = ".bin/show_keypress.sh"
description = "Show key press."
packages = ["xorg-xev"]
[bin-show_sxhkd_keybindings]
relpath = ".bin/show_sxhkd_keybindings.sh"
description = "Capture and show sxhkd keybindings."
[bin-status]
relpath = ".bin/status.sh"
description = "Check status of each git directory located in the current path."
packages = ["git"]
[bin-telpipe]
relpath = ".bin/telpipe"
description = "Send the output of the piped command to your telegram user."
[bin-telret]
relpath = ".bin/telret"
description = "Send the return code of the previous command to your telegram user."
[bin-tput_color_base16]
relpath = ".bin/tput_color_base16.sh"
description = "Show base16 fg/bg color combinations."
[bin-tput_color_table]
relpath = ".bin/tput_color_table.sh"
description = "Show all ANSI colors with their correspondent index."
[bin-vm]
relpath = ".bin/vm"
description = "Manage VirtualBox VM running without GUI."
packages = ["virtualbox"]
[bin-xr_color_scheme]
relpath = ".bin/xr_color_scheme.sh"
description = "Show first 21 colors from Xresources."
[bin-xr_wrapper_reloader]
relpath = ".bin/xr_wrapper_reloader.sh"
description = "Reload xrdb with custom script."

# Shell scripts (non-executable)
[sh-add_paths_to_variable]
relpath = ".sh/add_paths_to_variable.sh"
description = "Add new paths to a PATH-like variable."
[sh-del_paths_from_variable]
relpath = ".sh/del_paths_from_variable.sh"
description = "Delete paths from a PATH-like variable."
[sh-load_shell_scripts]
relpath = ".sh/load_shell_scripts.sh"
description = "Load shell scripts from a path or a directory."

# Editors
[nvim-init]
relpath = ".config/nvim/init.vim"
description = "Nvim configuration file."
packages = ["neovim"]
[vim-vimrc]
relpath = ".vimrc"
description = "Vim configuration file."
packages = ["vim"]

# File managers
[pcmanfm]
relpath = ".config/pcmanfm/default/pcmanfm.conf"
description = "LXDE file manager."
packages = ["pcmanfm"]

[ranger-commands]
relpath = ".config/ranger/commands.py"
[ranger-rc]
relpath = ".config/ranger/rc.conf"
[ranger-rifle]
relpath = ".config/ranger/rifle.conf"
[ranger-scope]
relpath = ".config/ranger/scope.sh"

# Git
[gitconfig]
relpath = ".gitconfig"
description = "Git global configuration."
packages = ["git", "dandavison/delta"]

[gitcommit]
relpath = ".gitcommit"
description = "Git commit message template."
packages = ["git"]

# Shell
[bash-bashrc]
relpath = ".bashrc"
description = "Main bash user configuration file."
[bash-profile]
relpath = ".bash_profile"
description = "Entrypoint for .bashrc file."

[bash-aliases]
relpath = ".config/bash/aliases.sh"
description = "Utils file where the alias are defined."
[bash-functions]
relpath = ".config/bash/functions.sh"
description = "Utils file where the functions are defined."
[bash-variables]
relpath = ".config/bash/variables.sh"
description = "Utils file where the variables are defined."
[bash-prompt]
relpath = ".config/bash/prompt.sh"
description = "Custom shell prompt."

[fish-config]
relpath = ".config/fish/config.fish"
description = "Fish shell main configuration file."
[fish-fishfile]
relpath = ".config/fish/fishfile"
description = "Fish shell file where the pluggins are defined."
packages = ["Fisher"]

# Terminals
[terminator-config]
relpath = ".config/terminator/config"
description = "Terminator configuration file."
packages = ["terminator"]

# Utils
[top-toprc]
relpath = ".config/procps/toprc"
description = "Top configuration file."

# Window managers config files

## Bspwm
[bspwm-autostart]
relpath = ".config/bspwm/autostart.sh"
description = "bspwm app-autostart script."
[bspwm-bspwmrc]
relpath = ".config/bspwm/bspwmrc"
description = "bspwm configuration file."
packages = ["bspwm"]

## Sxhkd
[sxhkd-sxhkdrc]
relpath = ".config/sxhkd/sxhkdrc"
description = "sxhkd configuration file."
packages = ["sxhkd"]

## Wal (pywal)
[wal-reload-services]
relpath = ".config/wal/reload_services.sh"
description = "Script to run after wal theme selection."
packages = ["python-pywal"]

## Rofi
[rofi-config]
relpath = ".config/rofi/config"
description = "Rofi configuration file."
packages = ["rofi"]
[rofi-config-wal-template]
relpath = ".config/wal/templates/colors-rofi-dark.rasi"
description = "Wal template for Rofi."
packages = ["python-pywal"]

## Dunst
[dunst-dunstrc]
relpath = ".config/dunst/dunstrc"
description = "Dunst notification daemon main configuration file."
packages = ["dunst"]
[dunst-dunstrc-wal-template]
relpath = ".config/wal/templates/colors-dunstrc"
description = "Dunst configuration template to use wal coloring. Don't use this one along with dunstrc file."
packages = ["python-pywall"]

## Polybar
[polybar-config]
relpath = ".config/polybar/config"
description = "Polybar main configuration file."
packages = ["aur/polybar"]

## Xresources
[xresources-edit]
relpath = ".Xresources.edit"
description = "Xresources script to safely edit .Xresources through .Xresources.src."
[xresources-src]
relpath = ".Xresources.src"
description = "Xresources brother."

# Tmux
[tmux-conf-local]
relpath = ".tmux.conf.local"
description = "Tmux personalization using oh my tmux config."
packages = ["tmux"]

[ncspot-config]
relpath = ".config/ncspot/config.toml"
description = "NCurses Spotify client."
packages = "ncspot"

