[package]
name = "wmutils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }

[profile.release]
opt-level = 3
debug = false

[[bin]]
name = "wlist"
path = "src/bin/wlist.rs"
