;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-line
        drag-stuff-right
        end-of-visual-line
        indent-for-tab-command
        kill-region
        markdown-backward-paragraph
        markdown-forward-paragraph
        markdown-outdent-or-delete
        mouse-set-region
        org-cycle
        org-self-insert-command
        overwrite-mode
        sh-assignment
        ))

(setq mc/cmds-to-run-once
      '(
        executable-interpret
        find-file
        ignore
        save-buffers-kill-terminal
        toggle-frame-fullscreen
        ))
